[package]
name = "stakedex_interface"
version = "0.1.0"
edition = "2021"

[dependencies.borsh]
workspace = true

[dependencies.solana-program]
workspace = true

[dependencies.serde]
optional = true
version = "^1.0"
